//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datosUsuario()
        {
            this.Licenciaturas = new HashSet<Licenciaturas>();
        }
    
        public string idtrabajador { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string RFC { get; set; }
        public string Categoria { get; set; }
        public string Plantel { get; set; }
        public string Correo { get; set; }
        public string PDF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licenciaturas> Licenciaturas { get; set; }
    }
}
