//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class documents
    {
        public int @int { get; set; }
        public string name { get; set; }
        public string realName { get; set; }
        public byte[] doc { get; set; }
    }
}
